with source as (
      select * from {{ source('PROD_RAW', 'VW_F_SHIPMENTSINVOICES') }})
select 
SHIP_INVOICE_KEY,
SBU_KEY,
ORDER_KEY,
SHIPMENT_DATE_KEY,
INVOICE_KEY,
INVOICE_DATE_KEY,
CUSTOMER_KEY,
SHIP_TO_GEOGRAPHY_KEY,
ITEM_KEY,
ITEM_ACCTG_CLASS_KEY,
BUSINESS_TEAM_KEY,
SHIP_FROM_WAREHOUSE_KEY,
TERRITORY_KEY,
SHIPPED_UNITS,
SHIPPED_DOLLARS,
ORDERED_UNITS,
IFF(
	"SHIPPED_UNITS" <> 0,
	("SHIPPED_DOLLARS"/"SHIPPED_UNITS")*"ORDERED_UNITS",
	0
) AS "ORDERED_DOLLARS",
'PROD_RAW.MTD' AS "SOURCE"
from source
where shipped_units <> 0
