with GLOBAL_EXECUTIVE_DATA as (
      select * from {{ source('PROD_AIDA', 'GLOBAL_EXECUTIVE_DATA') }}
),
 MATERIAL_MASTER as (
      select * from {{ source('PROD_AIDA', 'MATERIAL_MASTER') }}
)
select 
"DATE_OF_WEEK" AS "DATE_AS_OF",
CONCAT(COALESCE(TRIM("GPP_DIVISION"),''),
      COALESCE(TRIM("GPP_CATEGORY"),''),
	COALESCE(TRIM("GPP_PORTFOLIO"),'')) AS "GPP_KEY",
UPPER(CONCAT(COALESCE(TRIM("MATERIAL_CODE"),''))) AS "SKU_KEY",
CASE WHEN 
  UPPER(COALESCE(TRIM("DEMAND_GROUP"),'')) = 'NOT ASSIGNED' THEN 
  UPPER(CONCAT(COALESCE(TRIM("DEMAND_GROUP"),''),'-',COALESCE(TRIM("GLOBAL_REGION_CODE"),'')))
 ELSE UPPER(COALESCE(TRIM("DEMAND_GROUP"),'')) END as "MRKT_CHNL_KEY",
SUM(CAST("UFR_NET_ORDER_QTY" AS INT)) AS "UFR_NET_ORDER_QTY",
SUM(CAST("UFR_QTY" AS INT)) AS "UFR_QTY",
SUM(ROUND("UFR_GSV",2)) AS "UFR_GSV",
SUM(CAST("OTIF_NET_ORDER_QTY" AS INT)) AS "OTIF_NET_ORDER_QTY",
SUM(ROUND("UFR_NET_ORDER_GSV",2))::FLOAT AS "UFR_NET_ORDER_GSV",
SUM(ROUND("OTIF_NET_ORDER_GSV",2)) AS "OTIF_NET_ORDER_GSV",
SUM(CAST("OTIF_QTY" AS INT)) AS "OTIF_QTY",
SUM(ROUND("OTIF_GSV",2)) AS "OTIF_GSV",
UPPER("PLANT_CODE") AS "LOC_KEY",
'PROD_AIDA.AIRFREIGHT.GLOBAL_EXECUTIVE_DATA' AS "SOURCE"
from GLOBAL_EXECUTIVE_DATA AS  GED
left join MATERIAL_MASTER AS MM ON  GED."MATERIAL_CODE" = MM."MATERIAL_NAME"
GROUP BY ALL 