with SBD_UFR as (
    SELECT 
    DATE_AS_OF,
    SKU_KEY,
    MRKT_CHNL_KEY,
    LOC_KEY,
    SOURCE,
    OTIF_NET_ORDER_QTY,
    OTIF_NET_ORDER_GSV,
    OTIF_GSV,
    OTIF_QTY,
    UFR_QTY,
    UFR_GSV,
    UFR_NET_ORDER_QTY,
    UFR_NET_ORDER_GSV
    FROM {{ ref('_stg__Extract_UFR_data') }}
),
MTD_EXL as (
    SELECT
    DATE_AS_OF,
    SKU_KEY,
    MRKT_CHNL_KEY,
    LOC_ID AS "LOC_KEY",
    SOURCE,
    OTIF_NET_ORDER_QTY,
    OTIF_NET_ORDER_GSV,
    OTIF_GSV,
    OTIF_QTY,
    UFR_QTY,
    UFR_GSV,
    UFR_NET_ORDER_QTY,
    UFR_NET_ORDER_GSV
    FROM {{ ref('_stg_Extract_MTD_EXL_UFR') }}
),
TOTAL_UFR as (
    SELECT *
    FROM SBD_UFR
    UNION ALL
    SELECT *
    FROM MTD_EXL
)
SELECT 
DATE_AS_OF,
SKU_KEY,
MRKT_CHNL_KEY,
LOC_KEY,
SOURCE,
{# ROUND(SUM(OTIF_NET_ORDER_QTY),2) AS "OTIF_NET_ORDER_QTY",
ROUND(SUM(OTIF_NET_ORDER_GSV),2) AS "OTIF_NET_ORDER_GSV", #}
{{SUM_ROUND('OTIF_NET_ORDER_QTY')}} AS "OTIF_NET_ORDER_QTY",
{{SUM_ROUND('OTIF_NET_ORDER_GSV')}} AS "OTIF_NET_ORDER_GSV",
ROUND(SUM(OTIF_GSV),2) AS "OTIF_GSV",
ROUND(SUM(OTIF_QTY),2) AS "OTIF_QTY",
ROUND(SUM(UFR_NET_ORDER_QTY),2) AS "UFR_NET_ORDER_QTY",
ROUND(SUM(UFR_NET_ORDER_GSV),2) AS "UFR_NET_ORDER_GSV",
ROUND(SUM(UFR_QTY),2) AS "UFR_QTY",
ROUND(SUM(UFR_GSV),2) AS "UFR_GSV"
FROM TOTAL_UFR
GROUP BY ALL