WITH ufr_data as (
    select *
    FROM {{ ref('_1_Join_SBD_MTD_UFR') }}
),
gpp_join as (
    select UFR.*,
    GPP.BRAND_KEY,
    GPP.GPP_KEY
    from ufr_data as UFR
    LEFT OUTER JOIN {{ ref('_stg_SKU_GPP') }} AS GPP ON UFR.SKU_KEY = GPP.SKU_KEY
),
date_ as (
select 
gpp_join.*,
CAL.F_MONTH_DATE
from gpp_join
INNER JOIN ( SELECT "Date" , F_MONTH_DATE
                from {{ ref('_stg__DimCalendar') }} ) as CAL ON gpp_join.DATE_AS_OF = CAL."Date"
),
mrkt_join as (
    SELECT date_.*,
    IFF( MRKT."REGION" = 'NORTH AMERICA', 
            UPPER(CONCAT(COALESCE(TRIM("SKU_KEY"),''),COALESCE(TRIM(MRKT."MARKET CHANNEL"),''))),
            UPPER(CONCAT(COALESCE(TRIM("SKU_KEY"),''),COALESCE(TRIM(MRKT."ROC Dmd Grp"),'')))) as "NPD_KEY",
    'ACTUALS' AS "PROJECT MS STATUS"
    FROM date_ 
    LEFT OUTER JOIN ( SELECT MRKT_CHNL_KEY, "ROC Dmd Grp" , "MARKET CHANNEL" , "REGION" 
                        FROM {{ ref('_stg__Test_Dim_CON_MARKET_CHANNEL') }} ) AS MRKT ON date_.MRKT_CHNL_KEY = MRKT.MRKT_CHNL_KEY),
npg_tag as (
    select *
    from mrkt_join AS mrkt
    LEFT OUTER JOIN ( SELECT "PROGRAM ID" , "FUZZY_FLAG" , NPD_KEY ,"Yearly Outlook" , DATE_MY
                        FROM {{ ref('_stg__TEST_Support_Fact_npd_SKU_Incr') }}) AS TSNPD ON mrkt.NPD_KEY = TSNPD.NPD_KEY AND mrkt.F_MONTH_DATE = TSNPD.DATE_MY)

select
DATE_AS_OF,
SKU_KEY,
MRKT_CHNL_KEY,
LOC_KEY,
OTIF_NET_ORDER_QTY,
OTIF_NET_ORDER_GSV,
OTIF_GSV,
OTIF_QTY,
UFR_NET_ORDER_QTY,
UFR_NET_ORDER_GSV::FLOAT AS UFR_NET_ORDER_GSV ,
UFR_QTY,
UFR_GSV::FLOAT AS UFR_GSV ,
GPP_KEY,
BRAND_KEY,
SOURCE,
"PROGRAM ID",
CASE WHEN "Yearly Outlook" IS NULL THEN 'Core' ELSE "Yearly Outlook" END AS "Yearly Outlook" ,
CASE WHEN "FUZZY_FLAG" IS NULL THEN 'NO' ELSE "FUZZY_FLAG" END as "FUZZY_FLAG",
hash("DATE_AS_OF","SKU_KEY","MRKT_CHNL_KEY","LOC_KEY","SOURCE")::VARCHAR as "CATEGORICAL_HASH_KEY",
hash(OTIF_NET_ORDER_QTY::VARCHAR,OTIF_NET_ORDER_GSV::VARCHAR,OTIF_GSV,OTIF_QTY::VARCHAR,UFR_NET_ORDER_QTY::VARCHAR,UFR_NET_ORDER_GSV::VARCHAR,UFR_QTY::VARCHAR,UFR_GSV::VARCHAR)::VARCHAR as "NUMERIC_HASH_KEY",
hash("DATE_AS_OF","SKU_KEY","MRKT_CHNL_KEY","LOC_KEY","SOURCE",OTIF_NET_ORDER_QTY::VARCHAR,OTIF_NET_ORDER_GSV::VARCHAR,OTIF_GSV,OTIF_QTY::VARCHAR,UFR_NET_ORDER_QTY::VARCHAR,UFR_NET_ORDER_GSV::VARCHAR,UFR_QTY::VARCHAR,UFR_GSV::VARCHAR)::VARCHAR as "RCRD_HASH_KEY"
From npg_tag


