version: 2
sources:
  - name: TEST_MARTS
    database: TEST_MARTS
    schema: FINANCE
    tables:
      - name: VW_EPM_ALL_SCENARIOS
        quoting:
          identifier: true
  - name: OPG_PL
    database: DEV_AIDA
    schema: OPG_PL
    tables:
      - name: VW_PROFIT
        quoting:
          identifier: true
      - name: ENT_MAP
        quoting:
          identifier: true

  - name: PROD_RAW
    database: PROD_RAW
    schema: DCT
    tables:
      - name: DCT_BAR_ENTITY_ATTR
        quoting:
          identifier: true