version: 2
sources:
  - name: TEST_MARTS
    database: TEST_MARTS
    schema: FINANCE
    tables:
      - name: VW_EPM_ALL_SCENARIOS
        quoting:
          identifier: true
  - name: OPG_PL
    database: DEV_AIDA
    schema: OPG_PL
    tables:
      - name: VW_PROFIT
        quoting:
          identifier: true
